name: Docker image creation

on:
  push:
    tags:
      - "v*.*.*"
      
env:
  REGISTRY: ghcr.io
  APP_IMAGE_NAME: lrydzkowski/r-systems-ng-front
  
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Getting the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    
      - name: Repository checkout
        uses: actions/checkout@v2
        
      - name: Signing in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extracting metadata (tags, labels) for an application docker image
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}

      - name: Building an application docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}